[package]
name = "acg-candidate-graph"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
acg-core.workspace = true
acg-feedback.workspace = true
acg-predicate.workspace = true
acg-profile-graph.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
acg-symbolic-json.workspace = true
serde_json.workspace = true
